In [1]:
import pandas as pd
import os
import datetime
import numpy as np

In [2]:
def list_extractor(df, col):
    """
    @Alex
    Function that will extract a list with the items in a column given in the argument, without repited values
        Input:
            df      : Dataframe with the data
            col     : Column of interest
        Output:
            l_col   : List with the unique references of the desired column
    """
    l_col = df[col].tolist()
    l_col = list(dict.fromkeys(l_col))
    return l_col

def compare_list_and_keep_value(complete, dat_complete, filt):
    """
    @Alex
    Function that checkes two list and accumulates the values of the original one for the result of the filted one
    """
    
    if len(dat_complete) > len(filt):
        dat_filt=[0.]*len(filt)
        j = 0
        for i in range(len(complete)-1):
            try:
                if complete[i] in filt:
                    dat_filt[j] += dat_complete[i]
                    j += 1
                else:
                    dat_filt[j] += dat_complete[i]
            except:
                print("ERROR:",i," ",dat_complete[i])
    else:
     dat_filt = [0.] + dat_complete
    return dat_filt

In [3]:
recovered = pd.read_csv("https://covid19tracking.narrativa.com/csv/recovered.csv")
recovered

,Country_EN,Country_ES,Country_IT,Region,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,2020-01-28,...,2021-01-11,2021-01-12,2021-01-13,2021-01-14,2021-01-15,2021-01-16,2021-01-17,2021-01-18,2021-01-19,2021-01-20
0,Kenya,Kenia,Kenia,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,81101.0,81255.0,81667.0,81933.0,82195.0,83324.0,83350.0,83350.0,82478.0,82654.0
1,Lebanon,Líbano,Libano,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,143716.0,144857.0,145873.0,147746.0,147746.0,151080.0,153038.0,154608.0,156084.0,157202.0
2,Russia,Rusia,Russia,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,2771793.0,2796132.0,2824240.0,2851737.0,2879082.0,2905972.0,2929255.0,2947479.0,2970450.0,2995256.0
3,Zambia,Zambia,Zambia,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,20781.0,21074.0,21568.0,22504.0,24105.0,25106.0,26159.0,27327.0,28066.0,29775.0
4,Libya,Libia,Libia,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,81237.0,82229.0,83311.0,84245.0,85068.0,85068.0,86125.0,87197.0,88062.0,88930.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,Colombia,Colombia,Colombia,Putumayo,0.0,0.0,0.0,0.0,0.0,0.0,...,5742.0,5795.0,5822.0,5842.0,5886.0,5906.0,5955.0,6027.0,6094.0,6139.0
606,Colombia,Colombia,Colombia,Bolívar,0.0,0.0,0.0,0.0,0.0,0.0,...,53046.0,53570.0,54479.0,54847.0,55150.0,55380.0,55600.0,56205.0,56643.0,56950.0
607,Colombia,Colombia,Colombia,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,1632614.0,1646892.0,1665003.0,1683835.0,1698457.0,1711924.0,1729633.0,1754222.0,1769935.0,1786170.0
608,Mozambique,Mozambique,Mozambico,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,17623.0,18170.0,18282.0,18352.0,18371.0,18515.0,18607.0,18880.0,19132.0,19484.0
609,Nicaragua,Nicaragua,Nicaragua,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,4225.0,4225.0,4225.0,4225.0,4225.0,4225.0,4225.0,4225.0,4225.0,4225.0

In [4]:
df_required_countries = pd.read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")
df_required_countries

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61271,ZWE,Africa,Zimbabwe,2021-01-16,26881.0,772.0,911.714,683.0,17.0,28.571,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535
61272,ZWE,Africa,Zimbabwe,2021-01-17,27203.0,322.0,818.000,713.0,30.0,29.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535
61273,ZWE,Africa,Zimbabwe,2021-01-18,27892.0,689.0,799.286,773.0,60.0,35.000,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535
61274,ZWE,Africa,Zimbabwe,2021-01-19,28675.0,783.0,776.571,825.0,52.0,39.143,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535
61275,ZWE,Africa,Zimbabwe,2021-01-20,29408.0,733.0,736.000,879.0,54.0,41.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.535

In [8]:
#List with the original locations
location = list_extractor(df_required_countries,"location")

#dictionary with dates per conuntry of original frame
dic_required_countries = {pais:df_required_countries[df_required_countries["location"]==pais]["date"].values.tolist() for pais in location} 

#dictionary with all the possible dates
dates_required_countries = list_extractor(df_required_countries,"date")

#dict with the iso codes not included in the analysis and the country
dict_iso_included = {pais:df_required_countries[df_required_countries["location"]==pais]["iso_code"].values.tolist() for pais in location}

# In here I got the countries that appears in the recovered df
recovered_group = recovered.groupby("Country_EN").sum()

# delete the index to work with Country_EN
recovered_country = recovered_group.reset_index()

# List of the Countries in Country_EN
countries_rec = list_extractor(recovered_country,"Country_EN")

# Countries from countries_rec that NOT appear in location
dif_countries = [pais for pais in countries_rec if pais not in location]

# Extract the DF with the countries of interest
recovered_country = recovered_country[~recovered_country["Country_EN"].isin(dif_countries)]

# list of final countries
final_countries_rec = [pais for pais in countries_rec if pais not in dif_countries]

# future dictionary with the values
dic_values_date_filt={}

# list of conflict countries
conflict = []

origin_date_rec = datetime.datetime.strptime("2020-01-23", '%Y-%m-%d').date()
today = datetime.date.today()
today = today.strftime('%Y-%m-%d')
complete = [d.strftime('%Y-%m-%d') for d in pd.date_range("2020-01-23",today)]


# for each country in location...
for pais in location:
#... we check if it's in the list of available data and...
    # ... if it's in there, we extract the data from the begining of data (23-Jan-2020)
    if pais in final_countries_rec: 
        aux = recovered_country.loc[recovered_country["Country_EN"] == pais].values.tolist() 
        clean = aux[0][1:]

    #... if it's not there, we fullfill with NaN values
    else:
        aux = [np.nan]*len(dic_required_countries[pais])
        clean = aux
        conflict.append(pais)

    # finally, we fill with the information for country
    dic_values_date_filt [pais] = clean
    


#  for each country in location we...
for pais in location:
    # ...first avoid the conflictive data
    if pais not in conflict:
        # ... get the date of origin from required countries and transform it to date format
        pais_date = datetime.datetime.strptime(dic_required_countries[pais][0], '%Y-%m-%d').date()
                
        # ...if the 'pais_date' is older than 'origin_date_rec', we add the difference in value to  
        if pais_date < origin_date_rec:
            dic_values_date_filt[pais] = [0.]*(abs((pais_date-origin_date_rec).days)) + dic_values_date_filt[pais]

        # ... if the 'origin_date_rec' is older than 'pais_date', we substract as many data as needed
        elif pais_date > origin_date_rec:           
            dic_values_date_filt[pais] = compare_list_and_keep_value(complete, dic_values_date_filt[pais], dic_required_countries[pais])

# We finally build the dict from where we'll create the DF
loc = []
rec = []
dates = []
for pais in location:
    rec = rec + dic_values_date_filt[pais]
    loc = loc + [pais]*len(dic_values_date_filt[pais])
    dates = dates + dic_required_countries[pais]

final = {"location":loc,"date":dates,"recovered":rec}

# Creation of the Dataframe
result = pd.DataFrame(final)

# Reindex for merging purposes
df1 = df_required_countries.set_index(["location","date"])
df2 = result.set_index(["location","date"])

# Merge of both df
total = pd.concat([df1,df2], axis=1, join="inner")

# Final result
total

                       iso_code continent  total_cases  new_cases  \
location    date
Afghanistan 2020-02-24      AFG      Asia          1.0        1.0
            2020-02-25      AFG      Asia          1.0        0.0
            2020-02-26      AFG      Asia          1.0        0.0
            2020-02-27      AFG      Asia          1.0        0.0
            2020-02-28      AFG      Asia          1.0        0.0
...                         ...       ...          ...        ...
Zimbabwe    2021-01-16      ZWE    Africa      26881.0      772.0
            2021-01-17      ZWE    Africa      27203.0      322.0
            2021-01-18      ZWE    Africa      27892.0      689.0
            2021-01-19      ZWE    Africa      28675.0      783.0
            2021-01-20      ZWE    Africa      29408.0      733.0

                        new_cases_smoothed  total_deaths  new_deaths  \
location    date
Afghanistan 2020-02-24                 NaN           NaN         NaN
            2020-02-25                 NaN           NaN         NaN
            2020-02-26                 NaN           NaN         NaN
            2020-02-27                 NaN           NaN         NaN
            2020-02-28                 NaN           NaN         NaN
...                                    ...           ...         ...
Zimbabwe    2021-01-16             911.714         683.0        17.0
            2021-01-17             818.000         713.0        30.0
            2021-01-18             799.286         773.0        60.0
            2021-01-19             776.571         825.0        52.0
            2021-01-20             736.000         879.0        54.0

                        new_deaths_smoothed  total_cases_per_million  \
location    date
Afghanistan 2020-02-24                  NaN                    0.026
            2020-02-25                  NaN                    0.026
            2020-02-26                  NaN                    0.026
            2020-02-27                  NaN                    0.026
            2020-02-28                  NaN                    0.026
...                                     ...                      ...
Zimbabwe    2021-01-16               28.571                 1808.594
            2021-01-17               29.429                 1830.259
            2021-01-18               35.000                 1876.616
            2021-01-19               39.143                 1929.297
            2021-01-20               41.429                 1978.614

                        new_cases_per_million  ...  extreme_poverty  \
location    date                               ...
Afghanistan 2020-02-24                  0.026  ...              NaN
            2020-02-25                  0.000  ...              NaN
            2020-02-26                  0.000  ...              NaN
            2020-02-27                  0.000  ...              NaN
            2020-02-28                  0.000  ...              NaN
...                                       ...  ...              ...
Zimbabwe    2021-01-16                 51.941  ...             21.4
            2021-01-17                 21.665  ...             21.4
            2021-01-18                 46.357  ...             21.4
            2021-01-19                 52.681  ...             21.4
            2021-01-20                 49.317  ...             21.4

                        cardiovasc_death_rate  diabetes_prevalence  \
location    date
Afghanistan 2020-02-24                597.029                 9.59
            2020-02-25                597.029                 9.59
            2020-02-26                597.029                 9.59
            2020-02-27                597.029                 9.59
            2020-02-28                597.029                 9.59
...                                       ...                  ...
Zimbabwe    2021-01-16                307.846                 1.82
            2021-01-17                307.846                 1.82
            2021-01-18                307.846                 1.82
            2021-01-19                307.846                 1.82
            2021-01-20                307.846                 1.82

                        female_smokers  male_smokers  handwashing_facilities  \
location    date
Afghanistan 2020-02-24             NaN           NaN                  37.746
            2020-02-25             NaN           NaN                  37.746
            2020-02-26             NaN           NaN                  37.746
            2020-02-27             NaN           NaN                  37.746
            2020-02-28             NaN           NaN                  37.746
...                                ...           ...                     ...
Zimbabwe    2021-01-16             1.6          30.7                  36.791
            2021-01-17             1.6          30.7                  36.791
            2021-01-18             1.6          30.7                  36.791
            2021-01-19             1.6          30.7                  36.791
            2021-01-20             1.6          30.7                  36.791

                        hospital_beds_per_thousand  life_expectancy  \
location    date
Afghanistan 2020-02-24                         0.5            64.83
            2020-02-25                         0.5            64.83
            2020-02-26                         0.5            64.83
            2020-02-27                         0.5            64.83
            2020-02-28                         0.5            64.83
...                                            ...              ...
Zimbabwe    2021-01-16                         1.7            61.49
            2021-01-17                         1.7            61.49
            2021-01-18                         1.7            61.49
            2021-01-19                         1.7            61.49
            2021-01-20                         1.7            61.49

                        human_development_index  recovered
location    date
Afghanistan 2020-02-24                    0.498        0.0
            2020-02-25                    0.498        0.0
            2020-02-26                    0.498        0.0
            2020-02-27                    0.498        0.0
            2020-02-28                    0.498        0.0
...                                         ...        ...
Zimbabwe    2021-01-16                    0.535    15872.0
            2021-01-17                    0.535    16512.0
            2021-01-18                    0.535    17372.0
            2021-01-19                    0.535    18110.0
            2021-01-20                    0.535    19253.0

[61276 rows x 54 columns]